### PR TITLE
Allow usage of {:system, "VAR"} syntax in front_end config

### PR DESCRIPTION
**Pull request by DrunkenInfant**
Allow usage of {:system, "VAR"} syntax in front_end config.

This is needed to allow configuration in deployment instead of compilation. For example when hosting multiple instances of the same binary with different configuration requirements.

### CODE REVIEW

**Comment by DrunkenInfant** [comment]
You mentioned following the syntax of https://github.com/mustafaturan/authable/blob/master/lib/authable/config.ex. Do you mean you'd like a similar module in this project to reduce clutter in modules using configurations?

How would you feel about using this hex package, https://hexdocs.pm/app_config/AppConfig.html? A fairly simple addition to its code would be enough to allow nested configuration variables.

**Comment by mustafaturan** [comment]
I prefer not to add a new dependency

**Comment by DrunkenInfant** [comment]
Sorry for the delay. I hope the new version is more to your liking.

**Comment by DrunkenInfant** [comment]
Done :)

**Comment by mustafaturan** [comment]
Thanks for the contribution, I will bump the version soon

**Comment by mustafaturan** [comment]
Version updated, thanks again.

**Pull request merged**
